global:
  sysdig:
    region: "us2"
    settings:
      # enable prometheus exporter
      prometheus_exporter:
      #  connect_url: 192.168.1.63:10544
      enabled: true

  kspm:
    deploy: true

nodeAnalyzer:
  nodeAnalyzer:
    # legacy image scan
    imageAnalyzer:
      deploy: false
    # (legacy) compliance benchmark runner
    benchmarkRunner:
      deploy: false
    # legacy host scan
    hostAnalyzer:
      deploy: false
    # new runtime image scanner (vulnerability management)
    runtimeScanner:
      deploy: true
      settings:
        eveEnabled: true
    # New VM host scanner
    hostScanner:
      deploy: true

admissionController: 
  enabled: true
  scanner:
    enabled: false